services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - DOMAIN=${DOMAIN}
      - ENVIRONMENT=${ENVIRONMENT}
    restart: unless-stopped
    volumes:
      - ./src:/app/src
    container_name: fastapi-app
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:v2.52.0  # Última versão estável até maio/2025
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - monitoring
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:10.4.2  # Última versão estável até maio/2025
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    networks:
      - monitoring
    restart: unless-stopped
    volumes:
      - grafana-storage:/var/lib/grafana  # Persistência opcional
      - ./grafana/provisioning:/etc/grafana/provisioning

networks:
  monitoring:
    driver: bridge

volumes:
  grafana-storage: