{
 "title": "Fastapi-app",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Erro em tentativa de login",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(rate(auth_attempts_total{job=\"fastapi-app\", status=\"failed\"}[$__rate_interval]))\n/\nsum(rate(auth_attempts_total{job=\"fastapi-app\"}[$__rate_interval]))\n) * 100",
     "legendFormat": "Erro em tentativa de login"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(request_duration_seconds_count{job=\"fastapi-app\"}[$__rate_interval])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uso de CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"fastapi-app\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum(rate(request_duration_seconds_count{job=\"fastapi-app\"}[$__rate_interval])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Auth Attempts Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(auth_attempts_total{job=\"fastapi-app\", status=\"failed\"}[$__rate_interval]))/sum(rate(auth_attempts_total{job=\"fastapi-app\"}[$__rate_interval]))) * 100",
     "legendFormat": "Auth Attempts Error"
    }
   ]
  },
  {
   "title": "Uso de CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"fastapi-app\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}